from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.colors import green, red, grey, black
from datetime import datetime


LEFT = 50
RIGHT = 550
LINE_HEIGHT = 16


def draw_bar(c, x, y, width, score):
    filled = width * (score / 100)

    c.setFillColor(grey)
    c.rect(x, y, width, 14, fill=1, stroke=0)

    c.setFillColor(green if score >= 70 else red)
    c.rect(x, y, filled, 14, fill=1, stroke=0)

    c.setFillColor(black)
    c.setFont("Helvetica", 10)
    c.drawString(x + width + 8, y + 2, f"{score:.1f}%")


def draw_box_title(c, y, text):
    c.setFillColor(grey)
    c.rect(LEFT, y-4, RIGHT-LEFT, 18, fill=1, stroke=0)
    c.setFillColor(black)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(LEFT+6, y, text)


def write_wrapped_line(c, y, text):
    words = text.split(", ")
    line = ""

    for w in words:
        test = line + w + ", "
        if c.stringWidth(test, "Helvetica", 11) < (RIGHT-LEFT-20):
            line = test
        else:
            c.drawString(LEFT+10, y, line)
            y -= LINE_HEIGHT
            line = w + ", "

    if line:
        c.drawString(LEFT+10, y, line)

    return y - LINE_HEIGHT


def generate_pdf_report(filename,
                        resume_skills,
                        jd_skills,
                        gap_report,
                        similarity_score,
                        maturity_level,
                        ats_score,
                        verdict,
                        recommendations,
                        section_scores):

    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter
    y = height - 50

    # ===== HEADER =====
    c.setFont("Helvetica-Bold", 20)
    c.drawString(LEFT, y, "CareerLens-AI Recruiter Report")

    y -= 22
    c.setFont("Helvetica", 10)
    c.drawString(LEFT, y, f"Generated on: {datetime.now().strftime('%d %b %Y %H:%M')}")

    y -= 35

    # ===== ATS SCORE BLOCK =====
    draw_box_title(c, y, "ATS SCORES")
    y -= 30

    c.setFont("Helvetica-Bold", 11)

    c.drawString(LEFT, y, "Skill Match Score")
    y -= 18
    draw_bar(c, LEFT, y, 260, gap_report["score"])

    y -= 30
    c.drawString(LEFT, y, "Semantic Similarity")
    y -= 18
    draw_bar(c, LEFT, y, 260, similarity_score)

    y -= 30
    c.drawString(LEFT, y, f"Overall ATS Score: {ats_score}%")

    y -= 20
    c.drawString(LEFT, y, f"Resume Maturity Level: {maturity_level}")

    y -= 20
    c.drawString(LEFT, y, f"Recruiter Verdict: {verdict}")

    # ===== SECTION SCORES =====
    y -= 35
    draw_box_title(c, y, "Section-wise ATS Scores")
    y -= 22

    c.setFont("Helvetica", 11)
    for sec, sc in section_scores.items():
        c.drawString(LEFT+10, y, f"{sec.title()}: {sc}%")
        y -= 16

    # ===== SKILL SECTIONS =====
    def skill_section(title, skill_set):
        nonlocal y
        if y < 120:
            c.showPage()
            y = height - 50

        draw_box_title(c, y, title)
        y -= 22
        c.setFont("Helvetica", 11)

        skill_line = ", ".join(sorted(skill_set))
        y = write_wrapped_line(c, y, skill_line)
        y -= 10

    skill_section("Matched Skills", gap_report["matched"])
    skill_section("Missing Skills", gap_report["missing"])
    skill_section("Extra Skills", gap_report["extra"])

    # ===== RECOMMENDATIONS =====
    if y < 140:
        c.showPage()
        y = height - 50

    draw_box_title(c, y, "Learning Recommendations")
    y -= 22
    c.setFont("Helvetica", 11)

    for rec in recommendations:
        c.drawString(LEFT+10, y, "- " + rec)
        y -= 16

    # ===== FOOTER =====
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(LEFT, 30, "Generated by CareerLens-AI • ATS + NLP Resume Analyzer")

    c.save()
